     
version: '3' 
volumes:
  peer0.org2.mbe.com:
  peer1.org2.mbe.com:
networks:
    mbev1:
      external:
        name: mbev1
services:
  ca_org2:
    deploy:
      placement:
        constraints:
          - node.labels.name == worker1
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_org2
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.mbe.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.mbe.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - 8054:7054
    command: sh -c 'fabric-ca-server start -b mbev1org2:passw0rd'
    volumes:
      - ./crypto-config/peerOrganizations/org2.mbe.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_org2
    networks:
       mbev1:
         aliases:
          - ca.org2.mbe.com
    
  peer0_org2:
    deploy:
      placement:
        contraints:
          -node.labels.name == worker1
    container_name: peer0org2mbecom
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=mbev1
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org2.mbe.com
      - CORE_PEER_ADDRESS=peer0.org2.mbe.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.mbe.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.mbe.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.mbe.com:7051
      - CORE_PEER_LOCALMSPID=org2MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couch.peer0.org2.mbe.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=mbev1org2
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=passw0rd
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:7051
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.mbe.com/peers/peer0.org2.mbe.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.mbe.com/peers/peer0.org2.mbe.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org2.mbe.com:/var/hyperledger/production
    networks:
      - mbev1

  couch_peer0_org2:
    deploy:
      placement:
        contraints:
          -node.labels.name == worker1
    container_name: couch_peer0_org2
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=mbev1org2
      - COUCHDB_PASSWORD=passw0rd
    ports:
      - 5984:5984
    networks:
      - mbev1
    
  peer1_org2:
    deploy:
      placement:
        constraints:
          - node.labels.name == worker1
    container_name: peer1.org2.mbe.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=mbev1
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.org2.mbe.com
      - CORE_PEER_ADDRESS=peer1.org2.mbe.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.mbe.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.mbe.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.mbe.com:7051
      - CORE_PEER_LOCALMSPID=org2MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couch.peer1.org2.mbe.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=mbev1org2
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=passw0rd
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:7051
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.mbe.com/peers/peer1.org2.mbe.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.mbe.com/peers/peer1.org2.mbe.com/tls:/etc/hyperledger/fabric/tls
      - peer1.org2.mbe.com:/var/hyperledger/production
    networks:
      - mbev1

  # couch_peer1_org2:
  #   container_name: couch.peer1.org2.mbe.com
  #   image: hyperledger/fabric-couchdb
  #   environment:
  #     - COUCHDB_USER=mbev1org2
  #     - COUCHDB_PASSWORD=passw0rd
  #   ports:
  #     - 6984:5984
  #   networks:
  #     - mbev1
    
  cli_org2:
    container_name: cli-org2
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    deploy:
      placement:
        constraints:
          - node.labels.name == worker1
    environment:
      - SYS_CHANNEL=system-channel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/ordererOrganizations/mbemarket.com/orderers/orderer.mbemarket.com/msp/tlscacerts/tlsca.mbemarket.com-cert.pem
      - CC_PATH=/opt/gopath/src/github.com/chaincode
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=mbev1

      # - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org2.mbe.com:7051
      - CORE_PEER_LOCALMSPID=org2MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.mbe.com/peers/peer0.org2.mbe.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations//peer0.org2.mbe.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.mbe.com/peers/peer0.org2.mbe.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.mbe.com/users/Admin@org2.mbe.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    # command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/chaincode
      - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./cli-scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel
      - ./orderer-tls:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/orderer/tls
    depends_on:
      - peer0.org2.mbe.com
      - peer1.org2.mbe.com
    networks:
      - mbev1
